:wrench: [devops]

diff --git a/_deploy/hook b/_deploy/hook
--- a/_deploy/hook
+++ b/_deploy/hook
@@ -21,7 +21,7 @@ fi
 
 echo "sourcing .env"
 source ".env"
-echo "APP_PATH is ${APP_PATH} - required HOST/HTTPS_PORT is ${HOST}:${HTTPS_PORT}"
+echo "APP_PATH is ${APP_PATH} - required PHX_HOST is ${PHX_HOST}"
 
 now_in_unix_seconds=$(date +'%s')
 
@@ -44,7 +44,7 @@ git reset --hard origin/master
 function stop_app() {
 
   echo -e "\033[43m STOPPING OLD RELEASE \033[0m"
-  local pid=$(sudo lsof -i -P -n | { grep ":${HTTPS_PORT} (LISTEN)" || :; })
+  local pid=$(sudo lsof -i -P -n | { grep ":4000 (LISTEN)" || :; })
 
   case $pid in
   "")
@@ -52,7 +52,7 @@ function stop_app() {
     ;;
 
   *)
-    echo -e "  killing current process \033[31m$1\033[0m (running on \033[31m${HTTPS_PORT}\033[0m)"
+    echo -e "  killing current process \033[31m$1\033[0m (running on \033[31m4000\033[0m)"
     # get the last part of the sentence (space separated list of words)
     # lrwxrwxrwx 1 ec2-user ec2-user 0 Feb 17 08:34 /proc/23501/exe -> /var/app/movo_releases/1645086172/erts-12.1.5/bin/beam.smp
     local EXE_PATH=$(ls -l /proc/$1/exe | awk '{ print $NF }')
@@ -73,7 +73,7 @@ function stop_app() {
 }
 
 echo -e "\033[44m BUILDING NEW RELEASE \033[0m"
-echo -e "  ports HTTP=\033[34m${HTTP_PORT}\033[0m / HTTPS=\033[34m${HTTPS_PORT}\033[0m"
+echo -e "  ports HTTP=\033[34m${HTTP_PORT}\033[0m / HTTPS=\033[34m4000\033[0m"
 
 # get deps
 mix deps.get --only prod
@@ -122,7 +122,7 @@ sleep 3
 # Starting new app
 echo -e "\033[42m STARTING NEW RELEASE \033[0m"
 cmdf="${REL_BASE_PATH}/${now_in_unix_seconds}/bin/${APP_NAME} ${cmd}"
-echo -e "  starting (${cmd}) release \033[32m${now_in_unix_seconds}\033[0m on ports \033[32m${HTTPS_PORT}\033[0m"
+echo -e "  starting (${cmd}) release \033[32m${now_in_unix_seconds}\033[0m on ports \033[32m4000\033[0m"
 echo -e "  running: ${cmdf}"
 
 $cmdf
